# Generated by Django 2.1 on 2018-08-30 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20180828_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.Article'),
        ),
    ]
