# Generated by Django 2.1 on 2018-09-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20180830_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comments_sum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments_text',
            field=models.TextField(verbose_name='Поле комментария'),
        ),
    ]
