# Generated by Django 2.1 on 2018-09-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_auto_20180902_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_sum',
        ),
        migrations.AddField(
            model_name='article',
            name='article_comments_sum',
            field=models.IntegerField(default=0),
        ),
    ]
