# Generated by Django 2.1 on 2018-09-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_remove_article_article_comments_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_comment_sum',
            field=models.IntegerField(default=0),
        ),
    ]
