# Generated by Django 2.1 on 2018-09-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_article_article_comment_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='article_comments_sum',
            field=models.IntegerField(default=0),
        ),
    ]
