# Generated by Django 2.1 on 2018-09-04 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_comments_article_comments_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='article_comments_sum',
        ),
    ]
