# Generated by Django 2.1 on 2018-09-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0009_remove_comments_article_comments_sum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_comment_sum',
        ),
    ]
